# copyright:
# license: LICENSE.txt
name: LSASAF_env
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10
  - conda-forge::jupyterlab
  - conda-forge::jupyter
  - conda-forge::dask  
  - conda-forge::xarray
  - conda-forge::netcdf4
  - conda-forge::scipy
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::h5py
  - conda-forge::tqdm
  - conda-forge::shapely
  - conda-forge::pandas
